'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  /**
   * Model for Quote
   * 
   * This model is supposed to represent a quote sent back to a user after they reqeust a service from a shop
   */
  class Quote extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  Quote.init({
    /** 
     * The ID of the model isntance. The ID is autogenerated when a new model is created and is default UUID
     * @var UUID
     */
    id: {
      type:DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      unique: true 
    },
    /**
     * The estimated cost of labour for the request
     * @var FLOAT
     */
    labour: {
      type: DataTypes.FLOAT, 
      allowNull: false
    },
    /**
     * The estimated cost of parts for the request, stored as JSON so you may specify how much each part costs individually
     * @var JSON
     */
    parts: {
      type: DataTypes.JSON, 
      allowNull: false
    },
    /**
     * The estimated cost of additional fees for the request, stored as JSON so you may specify how much each fee costs individually
     * @var JSON
     */
    fees: {
      type: DataTypes.JSON, 
      allowNull: false
    },
    /**
     * The estimated discount for the request, stored as flat $ and not %
     * @var FLOAT
     */
    discount: {
      type: DataTypes.FLOAT, 
      allowNull: false
    },
    /**
     * The estimated total cost for the request
     * @var FLOAT
     */
    total: {
      type: DataTypes.FLOAT, 
      allowNull: false
    },
    /** 
     * A note tied to the quote explaining any concerns, fees, and anything else concerning the quote
     * @var STRING
     */
    note: {
      type: DataTypes.STRING, 
      allowNull: true
    }
  }, {
    sequelize,
    modelName: 'Quote',
  });
  return Quote;
};