'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  /**
   * Model for Ratings
   * 
   * This model ties a User model to a Shop model, acting as a rating from the user concerning the shop
   */
  class Rating extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  Rating.init({
    /** 
     * The ID of the model isntance. The ID is autogenerated when a new model is created and is default UUID
     * @var UUID
     */
    id: {
      type:DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      unique: true 
    },
    /** 
     * The ID of the User model the Rating is tied to
     * @var UUID
     */
    user_id: {
      type: DataTypes.UUID, 
      allowNull: false,
      references:{
        model: 'User',
        key: 'id'
      }
    },
    /** 
     * The ID of the Shop model the Rating is tied to
     * @var UUID
     */
    shop_id: {
      type: DataTypes.UUID, 
      allowNull: false,
      references:{
        model: 'Shop',
        key: 'id'
      }
    },
    /**
     * The comment left by the user concerning the shop
     * @var STRING
     */
    comment: {
      type: DataTypes.STRING, 
      allowNull: false
    },
    /**
     * The number of stars (1-5) the user gives a shop
     * @var INTEGER
     */
    star: {
      type: DataTypes.INTEGER, 
      allowNull: false
    },
    /**
     * The pricing rating (1-5) the user gives a shop
     * @var INTEGER
     */
    price: {
      type: DataTypes.INTEGER, 
      allowNull: false
    }
  }, {
    sequelize,
    modelName: 'Rating',
  });
  return Rating;
};