'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  /**
   * Model for Services
   * 
   * This model is to represent services that are provided by automobile repair shops. 
   * This model has a ManyToMany relationships with the Shops model.
   */
  class Service extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      Service.belongsTo(models.Shop)
    }
  }
  Service.init({
    /** 
     * The ID of the model isntance. The ID is autogenerated when a new model is created and is default UUID
     * @var UUID
     */
    id: {
      type:DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      unique: true 
    },
    /**
     * The type of service provided
     * @var STRING
     */
    type: {
      type: DataTypes.STRING, 
      allowNull: false
    },
    /**
     * The name of the service provided
     * @var STRING
     */
    name: {
      type: DataTypes.STRING, 
      allowNull: false
    },
  }, {
    sequelize,
    modelName: 'Service',
  });
  return Service;
};