'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  /**
   * Model for ShopService
   * 
   * This model ties a Shop model to a Service model, with the shop's assigned details about the service they provide.
   */
  class ShopService extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  ShopService.init({
    /** 
     * The ID of the model isntance. The ID is autogenerated when a new model is created and is default UUID
     * @var UUID
     */
    id: {
      type:DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      unique: true 
    },
    /**
     * The ID of the Shop model this ShopService is tied to
     * @var UUID
     */
    shop_id: {
      type: DataTypes.UUID, 
      allowNull: false,
      references:{
        model: 'User',
        key: 'id'
      }
    },
    /**
     * The ID of the Service model this ShopService is tied to
     * @var UUID
     */
    service_id: {
      type: DataTypes.UUID, 
      allowNull: false,
      references:{
        model: 'Service',
        key: 'id'
      }
    },
    /**
     * The description of the service
     * @var STRING
     */
    description: {
      type: DataTypes.STRING, 
      allowNull: false
    },    
    /**
    * The description of the service
    * @var INTEGER
    */
    price: {
      type: DataTypes.INTEGER, 
      allowNull: false
    }
  }, {
    sequelize,
    modelName: 'ShopService',
  });
  return ShopService;
};