'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  /**
   * Model for ShopAdmin
   * 
   * The model ties a User model to a Shop model, assigning the user as an administrator for the shop.
   */
  class ShopAdmin extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  ShopAdmin.init({
    /** 
     * The ID of the model isntance. The ID is autogenerated when a new model is created and is default UUID
     * @var UUID
     */
    id: {
      type:DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      unique: true 
    },
    /** 
     * The ID of the User model this ShopAdmin is tied to
     * @var UUID
     */
    user_id: {
      type: DataTypes.UUID, 
      allowNull: false,
      references:{
        model: 'User',
        key: 'id'
      }},
    /** 
     * The ID of the Shop model this ShopAdmin is tied to
     * @var UUID
     */
    shop_id: {
      type: DataTypes.UUID, 
      allowNull: false,
      references:{
        model: 'Shop',
        key: 'id'
      }
    }
  }, {
    sequelize,
    modelName: 'ShopAdmin',
  });
  return ShopAdmin;
};