'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  /**
   * Model for Shops
   * 
   * This model is used to represent automobile shops that vehicle owners will be able to view and shop owners will be able to create.
   * The Shop model has a OneToMany relationship to the Services model, and a ManyToMany relationship with the User model.
   */

  class Shop extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      Shop.hasMany(models.Service, {onDelete: 'CASCADE'})
      Shop.belongsToMany(models.User, {through: 'ShopAdmin'})
      Shop.belongsToMany(models.User, {through: 'Rating'})
    }
  }
  Shop.init({

    /** 
     * The ID of the model isntance. Is autogenerated when a new model is created and is default UUID
     * @var UUID
     */
    id: {
      type:DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      unique: true 
    },
    /** 
     * The name of the shop
     * @var STRING
     */
    name: {
      type: DataTypes.STRING, 
      allowNull: false
    },
    /**
     * The address of the shop
     * @var STRING
     */
    address: {
      type: DataTypes.STRING, 
      allowNull: false
    },
    /**
     * The phone number associated with the shop
     * @var STRING
     */
    phone: {
      type: DataTypes.STRING, 
      allowNull: false
    },
    /**
     * The email associated with the shop
     * @var STRING
     */
    email: {
      type: DataTypes.STRING, 
      allowNull: false
    },
    /**
     * The schedule/availability of the shop
     * @var JSON
     */
    time: {
      type: DataTypes.JSON, 
      allowNull: false
    },
    /**
     * A description of the shop
     * @var STRING
     */
    description: {
      type: DataTypes.STRING, 
      allowNull: false
    }
  }, {
    sequelize,
    modelName: 'Shop',
  });
  return Shop;
};